server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/caraquista/microservicios-curso
          search-paths: config-data
        bootstrap: true
  application:
    name: config-service